name: Deploy SafeEntry APIs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Connect to VM and Deploy
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_PRIVATE_KEY_PATH: ~/.ssh/id_rsa
      run: |
        ssh -i "$SSH_PRIVATE_KEY_PATH" "$SSH_USERNAME"@"$SSH_HOST" << 'EOF'
          mkdir -p /home/ubuntu/safeentry-deploy
          cd /home/ubuntu/safeentry-deploy

          git pull origin main

          docker-compose down
          docker-compose build
          docker-compose up -d

          echo "Deploy concluído!"
        EOF
